'use client';

// --- IMPORTS ---
import React, { useState } from 'react';
import { Zap, Download, PenTool, Globe, Cpu, LayoutTemplate } from 'lucide-react';

export default function StratOS() {
  const [url, setUrl] = useState('');
  const [notes, setNotes] = useState('');
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState<any>(null);
 
  // 1. ANALYSIS ENGINE
  const analyze = async () => {
    if (!url && !notes) return alert("Please provide a URL or Context Notes.");
    setLoading(true);
    try {
      const res = await fetch('/api/analyze', {
        method: 'POST',
        body: JSON.stringify({ url, context: notes })
      });
      const data = await res.json();
      if (data.error) throw new Error(data.error);
      setResult(data);
    } catch (e) {
      alert("Analysis error. Try adding more context notes.");
    } finally {
      setLoading(false);
    }
  };

  // 2. HIGH-FIDELITY CANVAS ENGINE
  const downloadAsset = () => {
    if (!result) return;
    const canvas = document.createElement('canvas');
    const ctx = canvas.getContext('2d');
    if (!ctx) return;

    // Set Resolution
    const W = 1080;
    const H = 1350;
    canvas.width = W;
    canvas.height = H;

    // --- A. BACKGROUND ---
    ctx.fillStyle = '#09090b'; // Zinc-950
    ctx.fillRect(0, 0, W, H);

    // --- B. AMBIENT GLOW ---
    const colors: any = {
      'bg-blue-600': '#2563eb', 'bg-emerald-500': '#10b981',
      'bg-orange-500': '#f97316', 'bg-purple-600': '#9333ea',
      'bg-slate-900': '#1e293b', 'bg-rose-500': '#f43f5e'
    };
    const accentHex = colors[result.brand_color] || '#2563eb';

    const grad = ctx.createRadialGradient(W, 0, 0, W, 0, 800);
    grad.addColorStop(0, accentHex);
    grad.addColorStop(1, 'rgba(9, 9, 11, 0)');
    ctx.globalAlpha = 0.2;
    ctx.fillStyle = grad;
    ctx.fillRect(0, 0, W, H);
    ctx.globalAlpha = 1.0;

    // --- C. FRAME ---
    ctx.strokeStyle = '#27272a'; // Zinc-800
    ctx.lineWidth = 4;
    ctx.strokeRect(40, 40, W - 80, H - 80);

    // --- D. TEXT CONTENT ---
   
    // Label
    ctx.fillStyle = accentHex;
    ctx.font = 'bold 36px Courier New, monospace';
    ctx.fillText(result.stat_label.toUpperCase(), 100, 180);

    // Big Stat
    ctx.fillStyle = '#ffffff';
    ctx.font = 'bold 160px Inter, Helvetica, sans-serif';
    ctx.fillText(result.stats, 90, 340);

    // Headline
    ctx.fillStyle = '#e4e4e7'; // Zinc-200
    ctx.font = 'bold 72px Inter, Helvetica, sans-serif';
   
    // Text Wrapping
    const words = result.headline.split(' ');
    let line = '';
    let y = 800;
    const maxWidth = 880;
    const lineHeight = 90;

    words.forEach((word: string) => {
      const testLine = line + word + ' ';
      const metrics = ctx.measureText(testLine);
      if (metrics.width > maxWidth && line !== '') {
        ctx.fillText(line, 100, y);
        line = word + ' ';
        y += lineHeight;
      } else {
        line = testLine;
      }
    });
    ctx.fillText(line, 100, y);

    // Accent Line
    ctx.fillStyle = accentHex;
    ctx.fillRect(100, y + 60, 150, 10);

    // Watermark
    ctx.fillStyle = '#3f3f46';
    ctx.font = '40px monospace';
    ctx.fillText("GENERATED BY STRATOS", 100, H - 100);

    // --- E. EXPORT ---
    const link = document.createElement('a');
    link.download = `stratos_${Date.now()}.png`;
    link.href = canvas.toDataURL('image/png');
    link.click();
  };

  return (
    <div className="min-h-screen bg-black text-white font-sans selection:bg-indigo-500 selection:text-white flex flex-col md:flex-row overflow-hidden relative">
     
      {/* Background Ambience */}
      <div className="absolute top-[-20%] left-[-10%] w-[500px] h-[500px] bg-indigo-900/20 rounded-full blur-[128px] pointer-events-none" />
      <div className="absolute bottom-[-20%] right-[-10%] w-[500px] h-[500px] bg-blue-900/20 rounded-full blur-[128px] pointer-events-none" />

      {/* SIDEBAR / CONTROLS */}
      <div className="w-full md:w-[480px] bg-zinc-950/80 backdrop-blur-xl border-r border-white/10 p-8 flex flex-col h-screen overflow-y-auto relative z-10">
       
        {/* Header */}
        <div className="mb-12 flex items-center gap-3">
          <div className="w-10 h-10 bg-gradient-to-br from-indigo-500 to-blue-600 rounded-lg flex items-center justify-center text-white font-bold text-xl shadow-lg shadow-indigo-500/20">S</div>
          <div>
            <h1 className="font-bold text-xl tracking-tight">StratOS <span className="text-zinc-600 font-normal">v2.0</span></h1>
            <p className="text-zinc-500 text-xs tracking-wider font-mono">INTELLIGENCE ENGINE</p>
          </div>
        </div>

        {/* Input Form */}
        <div className="space-y-8">
          <div className="space-y-2">
            <label className="text-xs font-bold text-zinc-400 tracking-wider flex items-center gap-2">
              <Globe size={14} className="text-indigo-500"/> TARGET SOURCE
            </label>
            <div className="group relative">
              <input
                className="w-full bg-zinc-900/50 border border-white/10 p-4 rounded-xl text-sm focus:border-indigo-500 focus:ring-1 focus:ring-indigo-500 outline-none transition-all placeholder:text-zinc-700"
                placeholder="https://company.com"
                value={url}
                onChange={e => setUrl(e.target.value)}
              />
              <div className="absolute inset-0 rounded-xl bg-gradient-to-r from-indigo-500/10 to-blue-500/10 opacity-0 group-hover:opacity-100 pointer-events-none transition-opacity" />
            </div>
          </div>

          <div className="space-y-2">
            <label className="text-xs font-bold text-zinc-400 tracking-wider flex items-center gap-2">
              <PenTool size={14} className="text-indigo-500"/> STRATEGIC CONTEXT
            </label>
            <textarea
              className="w-full bg-zinc-900/50 border border-white/10 p-4 rounded-xl text-sm focus:border-indigo-500 focus:ring-1 focus:ring-indigo-500 outline-none h-40 resize-none transition-all placeholder:text-zinc-700 leading-relaxed"
              placeholder="Paste press release text, key stats, or specific campaign goals here..."
              value={notes}
              onChange={e => setNotes(e.target.value)}
            />
          </div>

          <button
            onClick={analyze}
            disabled={loading}
            className={`w-full h-14 rounded-xl font-bold flex items-center justify-center gap-2 transition-all shadow-lg ${
              loading
                ? 'bg-zinc-800 text-zinc-400 cursor-not-allowed'
                : 'bg-white text-black hover:bg-zinc-200 hover:shadow-white/10 hover:scale-[1.01]'
            }`}
          >
            {loading ? (
              <span className="flex items-center gap-2">
                <Cpu size={18} className="animate-spin" /> PROCESSING DATA...
              </span>
            ) : (
              <span className="flex items-center gap-2">
                <Zap size={18} className="fill-black" /> EXECUTE STRATEGY
              </span>
            )}
          </button>
        </div>

        {/* Results Panel */}
        {result && (
          <div className="mt-12 pt-10 border-t border-white/10 animate-in slide-in-from-bottom-4 fade-in duration-500">
            <div className="flex items-center justify-between mb-4">
              <h3 className="text-xs font-bold text-zinc-500 tracking-wider">GENERATED COPY</h3>
              <div className="flex gap-2">
                 <span className="text-[10px] bg-indigo-500/10 text-indigo-400 px-2 py-1 rounded border border-indigo-500/20">AI_MODEL: GEMINI</span>
              </div>
            </div>
           
            <div className="bg-zinc-900/50 p-6 rounded-xl border border-white/5 space-y-4">
              <p className="text-sm text-zinc-300 leading-relaxed font-light">{result.tweet_body}</p>
              <div className="flex flex-wrap gap-2 pt-2 border-t border-white/5">
                {result.hashtags.split(' ').map((tag: string, i: number) => (
                  <span key={i} className="text-xs text-blue-400">{tag}</span>
                ))}
              </div>
            </div>
          </div>
        )}
       
        {/* Footer */}
        <div className="mt-auto pt-8 text-zinc-700 text-[10px] flex justify-between">
            <span>STRATOS ENGINE V2.0</span>
            <span>SECURE CONNECTION</span>
        </div>
      </div>

      {/* PREVIEW AREA */}
      <div className="flex-1 bg-black flex items-center justify-center p-10 relative overflow-hidden">
        {/* Grid Pattern */}
        <div className="absolute inset-0 opacity-20" style={{
            backgroundImage: `linear-gradient(to right, #333 1px, transparent 1px), linear-gradient(to bottom, #333 1px, transparent 1px)`,
            backgroundSize: '40px 40px'
        }}></div>
       
        {/* Radial Fade for Grid */}
        <div className="absolute inset-0 bg-gradient-to-t from-black via-transparent to-black pointer-events-none"></div>

        {result ? (
          <div className="flex flex-col items-center gap-8 animate-in zoom-in-95 duration-700 relative z-10">
            {/* The "Poster" Preview */}
            <div className="relative group">
               {/* Ambient Glow */}
               <div className={`absolute -inset-1 bg-gradient-to-br ${result.brand_color.replace('bg-', 'from-').replace('600', '500').replace('500', '400')} to-zinc-900 rounded-lg blur opacity-20 group-hover:opacity-40 transition duration-1000`}></div>
               
               {/* Preview Card */}
               <div className="w-[400px] h-[500px] bg-zinc-950 border border-zinc-800 shadow-2xl relative p-8 flex flex-col justify-between overflow-hidden rounded-lg">
                 
                  {/* Internal Glow */}
                  <div className={`absolute top-0 right-0 w-full h-full bg-gradient-to-bl ${result.brand_color.replace('bg-', 'from-').replace('600', '500')} to-transparent opacity-10 pointer-events-none`}></div>
                 
                  {/* Top Section */}
                  <div className="relative z-10 space-y-2 mt-4">
                    <p className={`font-mono text-sm font-bold ${result.brand_color.replace('bg-', 'text-')}`}>
                      {result.stat_label.toUpperCase()}
                    </p>
                    <h2 className="text-7xl font-bold tracking-tighter text-white leading-none">
                      {result.stats}
                    </h2>
                  </div>
                 
                  {/* Bottom Section */}
                  <div className="relative z-10 mb-8">
                    <h3 className="text-3xl font-bold leading-tight text-zinc-200">
                      {result.headline}
                    </h3>
                    <div className={`h-1 w-20 ${result.brand_color} mt-6`}></div>
                  </div>
                 
                  {/* Watermark */}
                  <div className="absolute bottom-4 left-8 text-[10px] text-zinc-600 font-mono">
                    GENERATED BY STRATOS
                  </div>
               </div>
            </div>

            <button
              onClick={downloadAsset}
              className="flex items-center gap-2 text-zinc-400 hover:text-white transition-colors text-xs tracking-widest uppercase font-bold border border-white/10 px-6 py-3 rounded-full hover:bg-white/5 hover:border-white/20"
            >
              <Download size={14} /> Download High-Res Asset
            </button>
          </div>
        ) : (
          <div className="text-zinc-800 flex flex-col items-center gap-6 animate-pulse">
            <LayoutTemplate size={64} strokeWidth={0.5} />
            <p className="tracking-[0.2em] text-xs font-bold">SYSTEM READY</p>
          </div>
        )}
      </div>
    </div>
  );
}